function [evs_used, ii_used, cc_P, tt_shift_P, cc_T, tt_shift_T] = xcorrsot(ddir, evs_str, ...
    pstation, plocation, tstation, tlocation)
% [evs_used, ii_used, cc_P, tt_shift_P, cc_T, tt_shift_T] = ...
%     XCORRSOT(ddir, evs_str, pstation, plocation, tstation, tlocation)
%
% Computes cross-correlation between P-phase and T-phase waveforms recorded
% at a station from repeating events. The output is also saved to
% ddir/xcorrsot_output.mat
%
% INPUT:
% ddir          directory to the sacfiles generated by QUERYSOT
% evs_str       event structs containing the following variables
%   - PreferredTime
%   - PreferredLatitude
%   - PreferredLongitude
%   - PreferredDepth
%   - PreferredMagnitudeValue
%   - PreferredMagnitudeType
%   - PublicId
%   - tT
% pstation      network.station name of the receiver for P-wave xcorr
% plocation     [lon lat] of pstation
% tstation      network.station name of the receiver for T-wave xcorr
% tlocation     [lon lat] of tstation
%
% OUTPUT:
% evs_used      events actually used for cross-correlation
% ii_used       index of the events actually used for cross-correlation
% cc_P          P-phase correlation coefficient between used events
% tt_shift_P    P-phase optimal timeshift between used events
% cc_T          T-phase correlation coefficient between used events
% tt_shift_T    T-phase optimal timeshift between used events
%
% SEE ALSO:
% IRISFETCH, QUERYSOT, VISUALIZESOT
%
% Last modifed by spipatprathanporn@ucsd.edu, 09/19/2026

% length of the event list
N = length(evs_str.PreferredTime);

% output format from instrument response remove function
resp_output_fmt = 'velocity';

%% Part 1
% compute the distance bewteen events
dx = sin(deg2rad(median(evs_str.PreferredLatitude))) .* ...
    deg2km(evs_str.PreferredLongitude - evs_str.PreferredLongitude');
dy = deg2km(evs_str.PreferredLatitude - evs_str.PreferredLatitude');
dz = evs_str.PreferredDepth - evs_str.PreferredDepth';
dd = sqrt(dx.^2 + dy.^2 + dz.^2);
clear dx dy dz;

% compute the origin datetime
evs_str.dt_origin = datetime(evs_str.PreferredTime, 'TimeZone', 'UTC', ...
    'Format', 'uuuu-MM-dd''T''HH:mm:ss.SSSSSS');


% compute P and S wave travel time to plocation
for ii = 1:N
    [evs_str.distkmP(ii), evs_str.distdegP(ii)] = ...
        grcdist([evs_str.PreferredLongitude(ii) ...
        evs_str.PreferredLatitude(ii)], plocation);
    tt = tauptime('mod', 'prem', 'dep', evs_str.PreferredDepth(ii), ...
        'ph', 'p,P', 'deg', evs_str.distdegP(ii));
    evs_str.tP_P(ii) = tt(1).time;
    tt = tauptime('mod', 'prem', 'dep', evs_str.PreferredDepth(ii), ...
        'ph', 's,S', 'deg', evs_str.distdegP(ii));
    evs_str.tS_P(ii) = tt(1).time;
end

% filtered out unusable events
dt_arrival = evs_str.dt_origin + seconds(evs_str.tP_P);
istooclose = and(abs(dt_arrival - dt_arrival') < minutes(1), ~eye(N));
whclose = any(istooclose, 1);
isusable = (dd <= 60);
isusable(whclose,:) = false;
isusable(:,whclose) = false;
wh = any(isusable, 1);
ii_used = indeks(1:N, wh);
fn = fieldnames(evs_str);
for ii = 1:length(fn)
    evs_str.(fn{ii}) = evs_str.(fn{ii})(wh);
end
dd = dd(wh, wh);
N = length(evs_str.PreferredTime);
clear dt_arrival istooclose isusable wh;

%% Part 2 Read and process P-wave
for ii = 1:N
    try
        % read local station seismograms for event ii
        dt_origin = evs_str.dt_origin(ii);
        dt_begin = dt_origin - minutes(1);
        dt_end = dt_origin + seconds(evs_str.tT(ii)) + minutes(10);
        fname = sprintf('%s.%s_%s.sac', pstation, dt_begin, dt_end);
        fname = replace(fname, '.000000', '');
        fname = fullfile(ddir, fname);
    
        [seisP, hdrP] = readsac(fname);
        [~, ~, ~, fs, ~, dts, ~] = gethdrinfo(hdrP);
        tP = seconds(dts - dt_origin);
        
        % remove instrument response
        sacpzfileP = [fname 'pz'];
        seisP = detrend(seisP, 2) .* shanning(length(seisP), 0.016);
        seisP = real(transfer(seisP, 1/fs, [0.01 0.02 8 10], ...
            resp_output_fmt, sacpzfileP, 'sacpz'));

        % downsample to 20 Hz if the sampling rate is 40 Hz
        if abs(fs - 40) < 0.001
            seisP = lowpass(seisP, fs, 10, 2, 2, 'butter', 'linear');
            tP = downsample(tP, 2);
            seisP = downsample(seisP, 2);
            fs = fs/2;
            hdrP.DELTA = hdrP.DELTA * 2;
            hdrP.NPTS = length(seisP);
            hdrP.E = hdrP.B + (hdrP.NPTS-1) * hdrP.DELTA;
        end
    
        % apply a bandpass filter
        seisP = bandpass(seisP, fs, 1, 3, 2, 2, 'butter', 'linear');
    
        % applying window
        winlen = min(50, 6*(evs_str.tS_P(ii)-evs_str.tP_P(ii)));
        win = evs_str.tP_P(ii) - 3 + [0 winlen];
        tr(ii).t = tP(and(tP>=win(1), tP<=win(2)));
        tr(ii).seis = seisP(and(tP>=win(1), tP<=win(2)));
    catch ME
        ME.getReport()
        tr(ii).t = nan;
        tr(ii).seis = nan;
    end
end

%% Part 3 Cross correlate P-wave
cc_P = nan(size(dd));
tt_shift_P = nan(size(dd));
for ii = 1:N
    % ignore event with no or very short seismogram
    if isscalar(tr(ii).t) || isempty(tr(ii).t) || tr(ii).t(end)-tr(ii).t(1) < 20
        continue
    end
    for jj = (ii+1):N
        % ignore event pairs with greater than 60 km of separation
        if dd(ii,jj) > 60
            continue
        end
        % ignore event with no or very short seismogram
        if isscalar(tr(jj).t) || isempty(tr(jj).t) || tr(jj).t(end)-tr(jj).t(1) < 20
            continue
        end
        % ignore event pairs with too close arrivals at pstation
        if abs((evs_str.dt_origin(ii)+seconds(evs_str.tP_P(ii))) - ...
                (evs_str.dt_origin(jj)+seconds(evs_str.tP_P(jj)))) < minutes(1)
            continue
        end
        try
            [t_shift, CCmax, lags, CC] = ccshift(tr(ii).seis, tr(jj).seis, ...
                datetime("today")+seconds(tr(ii).t(1)), ...
                datetime("today")+seconds(tr(jj).t(1)), ...
                fs, seconds(20), 'hard');
            cc_P(ii,jj) = CCmax;
            cc_P(jj,ii) = CCmax;
            tt_shift_P(ii,jj) = t_shift;
            tt_shift_P(jj,ii) = -t_shift;
            if CCmax > 0.8
                figure(11);
                clf
                set(gcf, 'Units', 'inches', 'Position', [0 1 5 5])
                subplot(311)
                plot(tr(ii).t, tr(ii).seis / max(abs(tr(ii).seis)), 'LineWidth', 1)
                xlim([min(tr(ii).t(1),tr(jj).t(1)) max(tr(ii).t(end),tr(jj).t(end))])
                ylim([-1.2 1.2])
                grid on
                yticks(-1:0.5:1)
                xlabel('time since origin (s)')
                title(sprintf('%s: Event %s', pstation, evs_str.PreferredTime{ii}))
                set(gca, 'FontSize', 11, 'Box', 'on', 'TickDir', 'out')
                subplot(312)
                plot(tr(jj).t, tr(jj).seis / max(abs(tr(jj).seis)), 'LineWidth', 1)
                xlim([min(tr(ii).t(1),tr(jj).t(1)) max(tr(ii).t(end),tr(jj).t(end))])
                ylim([-1.2 1.2])
                grid on
                yticks(-1:0.5:1)
                xlabel('time since origin (s)')
                title(sprintf('%s: Event %s', pstation, evs_str.PreferredTime{jj}))
                set(gca, 'FontSize', 11, 'Box', 'on', 'TickDir', 'out')
                subplot(313)
                plot(lags, CC, 'LineWidth', 1)
                grid on
                yticks(-1:0.5:1)
                xlim([-20 20])
                ylim([-1.05 1.05])
                xlabel('lag (s)')
                title(sprintf('Max CC: %.3f, at %.3f s', CCmax, t_shift))
                set(gca, 'FontSize', 11, 'Box', 'on', 'TickDir', 'out')
                set(gcf, 'Renderer', 'painters')
                figdisp(replace(sprintf('%s_%s_%s_%s', mfilename, pstation, ...
                    evs_str.dt_origin(ii), evs_str.dt_origin(jj)), ':', '.'), ...
                    [], [], 2, [], 'epstopdf')
            end
        catch ME
            ME.getReport()
        end
    end
end

%% Part 4 Read and process T-wave
for ii = 1:N
    try
        % read local station seismograms for event ii
        dt_origin = datetime(evs_str.PreferredTime(ii), 'TimeZone', 'UTC', ...
            'Format', 'uuuu-MM-dd''T''HH:mm:ss.SSSSSS');
        dt_begin = dt_origin - minutes(1);
        dt_end = dt_origin + seconds(evs_str.tT(ii)) + minutes(10);
    
        fname = sprintf('%s.%s_%s.sac', tstation, dt_begin, dt_end);
        fname = replace(fname, '.000000', '');
        fname = fullfile(ddir, fname);
    
        [seisT, hdrT] = readsac(fname);
        [~, ~, ~, fs, ~, dts, ~] = gethdrinfo(hdrT);
        tT = seconds(dts - dt_origin);
        
        % remove instrument response
        sacpzfileT = [fname 'pz'];
        seisT = detrend(seisT, 2) .* shanning(length(seisT), 0.016);
        seisT = real(transfer(seisT, 1/fs, [0.01 0.02 8 10], ...
            resp_output_fmt, sacpzfileT, 'sacpz'));

        % downsample to 20 Hz if the sampling rate is 40 Hz
        if abs(fs - 40) < 0.001
            seisT = lowpass(seisT, fs, 10, 2, 2, 'butter', 'linear');
            tT = downsample(tT, 2);
            seisT = downsample(seisT, 2);
            fs = fs/2;
            hdrT.DELTA = hdrT.DELTA * 2;
            hdrT.NPTS = length(seisT);
            hdrT.E = hdrT.B + (hdrT.NPTS-1) * hdrT.DELTA;
        end
    
        % apply a bandpass filter
        seisT = bandpass(seisT, fs, 1.5, 2.5, 2, 2, 'butter', 'linear');
    
        tr_T(ii).t = tT;
        tr_T(ii).seis = seisT;
    catch ME
        ME.getReport()
        tr_T(ii).t = nan;
        tr_T(ii).seis = nan;
    end
end

%% Part 5 Cross correlate T-wave
cc_T = nan(size(dd));
tt_shift_T = nan(size(dd));
for ii = 1:N
    % skip NaN traces
    if isscalar(tr_T(ii).t)
        continue
    end
    try
        fs = (length(tr_T(ii).t) - 1) / (tr_T(ii).t(end) - tr_T(ii).t(1));
        % cc(ii,ii) = 1;
        % tt_shift(ii,ii) = 0;
    catch ME
        ME.getReport();
        continue
    end
    for jj = (ii+1):N
        % ignore event pairs with greater than 60 km of separation or
        % P-wave correlation coefficients smaller than 0.9
        if dd(ii,jj) > 60 || cc_P(ii,jj) < 0.9
            continue
        end
        % skip NaN traces
        if isscalar(tr_T(jj).t) || isnan(tt_shift_P(ii,jj))
            continue
        end
        try
            % window for first trace
            win1 = evs_str.tT(ii) + [10 70];

            % apply window for first trace
            tr_T1_t = tr_T(ii).t(and(tr_T(ii).t >= win1(1), tr_T(ii).t <= win1(2)));
            tr_T1_seis = tr_T(ii).seis(and(tr_T(ii).t >= win1(1), tr_T(ii).t <= win1(2)));

            % window for second trace
            win2 = evs_str.tT(jj) + [10 70];

            % apply window for second trace
            t2 = tr_T(jj).t + tt_shift_P(ii, jj);
            tr_T2_t = t2(and(t2 >= win2(1), t2 <= win2(2)));
            tr_T2_seis = tr_T(jj).seis(and(t2 >= win2(1), t2 <= win2(2)));

            [t_shift, CCmax, lags, CC] = ccshift(tr_T1_seis, tr_T2_seis, ...
                datetime("today")+seconds(tr_T1_t(1)), ...
                datetime("today")+seconds(tr_T2_t(1)), ...
                fs, seconds(20), 'hard');
            cc_T(ii,jj) = CCmax;
            cc_T(jj,ii) = CCmax;
            tt_shift_T(ii,jj) = t_shift;
            tt_shift_T(jj,ii) = -t_shift;
            if CCmax > 0.6
                figure(11);
                clf
                set(gcf, 'Units', 'inches', 'Position', [0 1 5 5])
                subplot(311)
                plot(tr_T1_t, tr_T1_seis / max(abs(tr_T1_seis)), 'LineWidth', 1)
                xlim([min(tr_T1_t(1),tr_T2_t(2)) max(tr_T1_t(end),tr_T2_t(end))])
                ylim([-1.2 1.2])
                grid on
                yticks(-1:0.5:1)
                xlabel('time since origin (s)')
                title(sprintf('%s: Event %s', tstation, evs_str.PreferredTime{ii}))
                set(gca, 'FontSize', 11, 'Box', 'on', 'TickDir', 'out')
                subplot(312)
                plot(tr_T2_t, tr_T2_seis / max(abs(tr_T2_seis)), 'LineWidth', 1)
                xlim([min(tr_T1_t(1),tr_T2_t(2)) max(tr_T1_t(end),tr_T2_t(end))])
                ylim([-1.2 1.2])
                grid on
                yticks(-1:0.5:1)
                xlabel(sprintf('time since origin (s): corrected by %.3f s', tt_shift_P(ii,jj)))
                title(sprintf('%s: Event %s', tstation, evs_str.PreferredTime{jj}))
                set(gca, 'FontSize', 11, 'Box', 'on', 'TickDir', 'out')
                subplot(313)
                plot(lags, CC, 'LineWidth', 1)
                grid on
                yticks(-1:0.5:1)
                xlim([-20 20])
                ylim([-1.05 1.05])
                xlabel('lag (s)')
                title(sprintf('Max CC: %.3f, at %.3f s', CCmax, t_shift))
                set(gca, 'FontSize', 11, 'Box', 'on', 'TickDir', 'out')
                set(gcf, 'Renderer', 'painters')
                figdisp(replace(sprintf('%s_%s_%s_%s', mfilename, tstation, ...
                    evs_str.dt_origin(ii), evs_str.dt_origin(jj)), ':', '.'), ...
                    [], [], 2, [], 'epstopdf')
            end
        catch ME
            ME.getReport()
        end
    end
end

%% Part 6 filter out for unused event
A = and(dd <= 60, and(cc_P >= 0.9, cc_T >= 0.6));
whA = any(A,1);
fn = fieldnames(evs_str);
for ii = 1:length(fn)
    evs_used.(fn{ii}) = evs_str.(fn{ii})(whA);
end
ii_used = ii_used(whA);
cc_P = cc_P(whA,whA);
cc_T = cc_T(whA,whA);
tt_shift_P = tt_shift_P(whA,whA);
tt_shift_T = tt_shift_T(whA,whA);
% save the output
sname = fullfile(ddir, sprintf('%s_output.mat', mfilename));
evs_str = evs_used;
dd = dd(whA,whA);
save(sname, 'cc_P', 'cc_T', 'dd', 'evs_str', 'tt_shift_P', 'tt_shift_T');
fprintf('The output is saved to %s\n', sname);
end